// src/utils/dummyData.js
export const events = [
    {
      id: 1,
      name: "Rock Concert",
      date: "2025-03-20",
      description: "An exciting rock concert with live bands.",
      availableTickets: 50,
      image: "public/Rock_Concert.jpeg",
      category: "Music",
      location: "New York",
    },
    {
      id: 2,
      name: "Movie Night",
      date: "2025-04-15",
      description: "Join us for a movie marathon of the latest blockbusters.",
      availableTickets: 100,
      image: "public/Movie.jpeg",
      category: "Movie",
      location: "Los Angeles",
    },
    {
      id: 3,
      name: "Tech Conference",
      date: "2025-05-10",
      description: "A conference on the latest trends in technology.",
      availableTickets: 30,
      image: "public/Tech.jpeg",
      category: "Technology",
      location: "San Francisco",
    },
    {
      id: 4,
      name: "Jazz Festival",
      date: "2025-06-05",
      description: "Experience an evening of smooth jazz and great food.",
      availableTickets: 40,
      image: "public/Jazz.jpeg",
      category: "Music",
      location: "Chicago",
    },
    {
      id: 5,
      name: "Startup Meetup",
      date: "2025-07-12",
      description: "Meet like-minded entrepreneurs and pitch your ideas.",
      availableTickets: 20,
      image: "public/Startup.jpeg",
      category: "Business",
      location: "New York",
    },
    {
      id: 6,
      name: "Art Exhibition",
      date: "2025-08-22",
      description: "Showcasing contemporary artworks from local artists.",
      availableTickets: 60,
      image: "public/Art.jpeg",
      category: "Art",
      location: "San Francisco",
    },
    {
      id: 7,
      name: "Coding Bootcamp",
      date: "2025-09-30",
      description: "An intensive coding bootcamp for aspiring developers.",
      availableTickets: 25,
      image: "public/Coding.jpeg",
      category: "Technology",
      location: "Seattle",
    },
    {
      id: 8,
      name: "Football Match",
      date: "2025-10-14",
      description: "Watch the big match between two top teams live!",
      availableTickets: 80,
      image: "public/Football.jpg",
      category: "Sports",
      location: "Los Angeles",
    },
    {
      id: 9,
      name: "Yoga Workshop",
      date: "2025-11-05",
      description: "A relaxing and rejuvenating yoga session for all levels.",
      availableTickets: 35,
      image: "public/Yoga.jpg",
      category: "Wellness",
      location: "Miami",
    },
    {
      id: 10,
      name: "Comedy Show",
      date: "2025-12-18",
      description: "Laugh out loud with top comedians performing live.",
      availableTickets: 45,
      image: "public/Comedy.jpg",
      category: "Entertainment",
      location: "Las Vegas",
    },
    {
      id: 11,
      name: "Photography Workshop",
      date: "2026-01-10",
      description: "Learn the secrets of professional photography.",
      availableTickets: 15,
      image: "public/Photography.jpeg",
      category: "Photography",
      location: "San Diego",
    },
    {
      id: 12,
      name: "Book Reading",
      date: "2026-02-20",
      description: "Meet your favorite author and discuss their latest book.",
      availableTickets: 50,
      image: "public/Book.webp",
      category: "Literature",
      location: "Boston",
    },
  ];
  